### ISSUE TITLE
[Feature] Add a way to shift an image position

### ISSUE THREAD

**Issue by demongund** [TaleSpire-Modding/ImageToPlanePlugin#2]
As a builder who is using a 2d map as a base and putting tiles/assets on top, I want a way to shift the image on the x and y axis a little bit, so that I can more easily align the image grid with the talespire grid.

Acceptance Criteria
USE CASE - A builder has modified an image so that the grid is 40x40 pixels but can't quite get the image size/position correct so the grid lines align in TaleSpire.
* There is  way to shift the displayed 2d image on the x and y axis to align the grids

Ideas
* Pressing a key to open a dialog that displays the 'origin' position of the image (0,0) and a text field which allows the position to be changed (0,10).
* Pressing a key activates a way to use the arrow keys to shift the image

**Comment by HolloFox** [comment]
was implemented.
