### ISSUE TITLE
Pluging not opening img selection

### ISSUE THREAD

**Issue by sesael** [TaleSpire-Modding/ImageToPlanePlugin#5]
Hi!, 

I just installed the plugin but when i click on "Open Board Locally Instead" nothing happens. Also, the mod command prompt shows this message:

> [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> Stack trace:
> SystemMessageTextField.PressCancelBtn () (at <9e65e0ef410b4d8586ac5abc69490a81>:0)
> UnityEngine.Events.InvokableCall.Invoke () (at <34494dee0a8743c49ad9dc4c9c1f32e6>:0)
> UnityEngine.Events.UnityEvent.Invoke () (at <34494dee0a8743c49ad9dc4c9c1f32e6>:0)
> UnityEngine.UI.Button.Press () (at <5080be49902a4bea80d9d7ec88d1f0aa>:0)
> UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <5080be49902a4bea80d9d7ec88d1f0aa>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <5080be49902a4bea80d9d7ec88d1f0aa>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <5080be49902a4bea80d9d7ec88d1f0aa>:0)
> UnityEngine.EventSystems.EventSystem:Update()

Any idea what could be causing it?

Thanks for the help in advance!

**Comment by HolloFox** [comment]
This error is due to a missing dll. When I get the chance, I aim to re-release the plugin with the dll to fix this error. This may be due to the HF update as dlls were updated and the dependent dll was removed.

**Comment by HolloFox** [comment]
Fixed with the winform patch that I released.
